# Generated by Django 4.2.5 on 2023-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=40)),
                ('s_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('kcse_index', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('birth_cert_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_name', models.TimeField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
    ]
