# Generated by Django 4.2.5 on 2023-11-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Birth_Certificate_No',
        ),
    ]
