# Generated by Django 4.2.5 on 2023-11-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Payment_Id',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
