# Generated by Django 4.2.5 on 2023-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='birth_cert_no',
            new_name='Birth_Certificate_No',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='f_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='kcse_index',
            new_name='KCSE_Index',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='l_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='s_name',
            new_name='Second_Name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst_name',
            new_name='Institution_Name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='ministry_id',
            new_name='Ministry_Id',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='type_id',
            new_name='Type_Id',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='ministry',
            old_name='min_name',
            new_name='Ministry_Name',
        ),
        migrations.RenameField(
            model_name='ministrytype',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='ministrytype',
            old_name='type_name',
            new_name='Type_Name',
        ),
    ]
