# Generated by Django 4.2.5 on 2023-11-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_remove_applicant_birth_certificate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minsubjectcategory',
            name='Grade_Id',
        ),
        migrations.DeleteModel(
            name='ClusterCategory',
        ),
    ]
