# Generated by Django 4.2.5 on 2023-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_remove_application_payment_id_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Course_Rank',
            field=models.CharField(choices=[(1, '1(a)'), (2, '1(b)'), (3, '1(c)'), (4, '2'), (5, '3'), (6, '4')], max_length=2),
        ),
    ]
