# Generated by Django 4.2.5 on 2023-10-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_rename_birth_cert_no_applicant_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='Ministry_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.ministry'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='Type_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.ministrytype'),
        ),
    ]
