# Generated by Django 4.2.5 on 2023-11-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_remove_minsubjectcategory_grade_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmincategory',
            name='Grade_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.grade'),
        ),
    ]
