# Generated by Django 4.2.5 on 2023-10-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_alter_institution_ministry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cluster_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterSubjectCategory',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cluster_Subject_Category_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Grade_Name', models.CharField(max_length=200)),
                ('Grade_Value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Applicant_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.applicant')),
                ('Payment_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=200)),
                ('Course_Code', models.PositiveIntegerField()),
                ('Cost', models.PositiveIntegerField()),
                ('Capacity', models.PositiveIntegerField()),
                ('Cluster_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.cluster')),
                ('Institution_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterSubject',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cluster_Subject_Name', models.CharField(max_length=200)),
                ('Cluster_Category_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.clustersubjectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Applicant_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.applicant')),
            ],
        ),
    ]
