# Generated by Django 4.2.5 on 2023-11-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_subjectmincategory_grade_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterMinGrade',
        ),
    ]
