# Generated by Django 4.2.5 on 2023-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_alter_application_course_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Course_Rank',
            field=models.IntegerField(choices=[(1, '1(a)'), (2, '1(b)'), (3, '1(c)'), (4, '2'), (5, '3'), (6, '4')]),
        ),
    ]
