# Generated by Django 4.2.5 on 2023-11-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_delete_clustermingrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Cost',
            new_name='Year_1_Course_Cost',
        ),
    ]
